import {StyleSheet} from 'react-native';


export const globalStyles = StyleSheet.create({
    container:{
        flex:1,
        justifyContent:'center',
        alignItems:'center',
    },
    h1:{
        fontSize:64,
        fontFamily:'Roboto-Medium',
    },
    h2:{
        fontSize:48,
        fontFamily:'Roboto-Medium',
    },
    h3:{
        fontSize:36,
        fontFamily:'Roboto-Medium',
    },
    h4:{
        fontSize:24,
        fontFamily:'Roboto-Medium',
    },
    h5:{
        fontSize:20,
        fontFamily:'Roboto-Medium',
    },
    h6:{
        fontSize:18,
        fontFamily:'Roboto-Medium',
    },
    sub1:{
        fontSize:16,
        fontFamily:'Roboto-Medium',
    },
    sub2:{
        fontSize:64,
        fontFamily:'Roboto-Regular',
    },
    body1:{
        fontSize:14,
        fontFamily:'Roboto-Medium',
    },
    body2:{
        fontSize:14,
        fontFamily:'Roboto-Regular',
    },
    body3:{
        fontSize:12,
        fontFamily:'Roboto-Medium',
    },
    body4:{
        fontSize:12,
        fontFamily:'Roboto-Regular',
    },
    legenda1:{
        fontSize:10,
        fontFamily:'Roboto-Medium',
    },
    legenda2:{
        fontSize:10,
        fontFamily:'Roboto-Regular',
    },
    mediumButtonStyle:{
        fontSize:14,
        fontFamily:'Roboto-Medium',
        marginTop:"3.59375%",
        minHeight:40,
        minWidth:"33.33%",
        marginBottom:"3%",
        alignItems:"center",
        justifyContent:"center",
        borderRadius:5,
        backgroundColor: '#740300',
        elevation:3,
    },
    normalInput:{
        minHeight: 45,
        marginTop:"3.125%",
        minWidth:"88%",
        borderRadius:8,
        backgroundColor:"#E5E5E5",
        paddingLeft:"5%"
    },
});
